### PR TITLE
DV instance on CP4D

### PR DESCRIPTION
**Pull request by spansare**

### CODE REVIEW

**Comment by triceam** [comment]
It looks like automation is failing.  I suspect this is actually b/c the CP4D cluster doesn't have cp4d deployed yet (@balasgit was working on the cp4d deployment module changes).

**Comment by balasgit** [comment]
[@amtrice](https://ibm-cloudplatform.slack.com/team/W3G3DFVU1) - Last week (till this monday), I was testing specifically CP4D - DB2WH module which i updated to operator (& Helm) . I didn’t deploy any other CP4D modules since cluster had all those modules installed earlier.  During DB2-WH testing, I noticed those namespaces exist which i shared earlier.  Ping me anytime as we can have quick call to sort this out.
FYI I checked above 2 modules automation which shows workflow fail happened 15 / 19 days ago
https://github.com/cloud-native-toolkit/terraform-gitops-cp-data-virtualization/actions (19 days ago last test failed)
https://github.com/cloud-native-toolkit/terraform-gitops-cp-db2-oltp/actions ( 15 days ago).

**Comment by balasgit** [comment]
Team - Here is additional information if someone reading this PR 

- Andrew tagged & asked me if i am making any changes to CP4D since the CP4D build was failing as Snehal create PR.
- I responded back to Andrew saying "I am only working on DB2WH modules and I am not touching other modules".

hope this clarifies :-)

**Comment by triceam** [comment]
Agreed, we aligned and made sure nobody is stepping on anyone else's work.  We're working in parallel on separate, but related, efforts.

**Review by sgumpana — APPROVED** [review]

**Pull request merged**
